WLS-313 enhanced plugin to update recursively
waylayio/Sensors pull request #75
Opened 2022-08-16 13:32 UTC by paul-cioroianu-waylay

2022-08-16 19:51 UTC, francisdb commented
Can you add a test for `createResourceHierarchy`?

2022-08-16 19:54 UTC, francisdb commented
Hmm, if the mocking of waylay js is not too much work? Or you provide it the update function. Not a hard requirement but always nice to have a safeguard for future modifications.

2022-08-17 07:28 UTC, paul-cioroianu-waylay commented
> 

I've looked through a few of the plugins and saw that there aren't any tests added so I've left it as it was. But yes, should've added new ones. Talked with Claudiu and he showed me how to improve the tests. Added a few tests that check the logic now :)

2022-08-17 08:40 UTC, francisdb approved these changes
Note to self. One day we should try to have locked dependencies for these plugins

2022-08-17 08:45 UTC, francisdb commented
@brunoballekens is this something we want on the backend side?

2022-08-17 09:07 UTC, brunoballekens requested changes
I don't think we want to change the `updateMetadata` plugin, which is used by a lot of customers with this very specific behaviour ? I would create a new plugin (e.g. named createResourceHierarchy) for this?

2022-08-17 09:13 UTC, brunoballekens commented
> @brunoballekens is this something we want on the backend side?

hmm, I was working on some improvements to add multiple resources in one go/call. I don't remember if it was only add or also patch/update.

2022-08-17 10:00 UTC, mfagadar commented on plugins/updateMetadata/updateMetadataRecursively.test.js
> +    await expect(runPlug(script, options, waylay)).resolves.toEqual({ "observedState": "Success", "rawData": { "response": {} } })
Shouldn't rawData equal the metadata of the created properties?

2022-08-17 10:09 UTC, mfagadar commented
@brunoballekens, the change is backwards compatible and the upgrade is transparent. The new plug version adds the capability to define a hierarchy of resources but preserves previous functionality and it can be used to manipulate resources individually the same way it was used in the past.  

Were we to create a new sensor, the new sensor would 100% incorporate the current `updateMetadata` sensor functionality, with exactly the same contract (properties, states, output). It would be confusing for the user which one to use and we would need to maintain 2 plugs instead of one with no added value on the old one, that being the reason to upgrade `updateMetadata` instead.

2022-08-17 10:14 UTC, brunoballekens commented
I don't think it is backward compatible.
If you previously used it to update a resource e.g to 
``` 
{
           "myRef" : {
                 "$ref" : "/resources/theReferencedResource"
                 "role" : "this is my role"
            }
}
```
the update of the plugin would create/update a resource `theReferencedResource` and set a `role` key ?

2022-08-17 10:58 UTC, mfagadar commented
Indeed, the new version allows to create the referenced resource if it does not exist and also update the properties of a linked resource (newly created or already existing). This is something we need and would be beneficial to provide for customer projects that rely on a structured approach to resources, like TCL does.

For backwards compatibility, nothing prevents the user from using the plugin in the old way, by just providing the reference to the linked resource with no additional properties.

```
{
   "myRef" : {
      "$ref" : "/resources/theReferencedResource"
   }
}
```

Hence, the payloads currently used by customers will continue to work as expected, with one difference (which I assume is the source of the non-backward compatible discussion): the plug will not create orphan references, as `theReferencedResource` will be created if not present. I am currently not aware of any customer project that requires the capability to set links to non-existing resources.

If this is needed and we can argument the reason why, we can easily adapt the implementation to only create the referenced resource if at least one additional property is provided. Shall we proceed that way?

2022-08-17 11:07 UTC, brunoballekens commented
Since it is a major change in the semantic of the plug, I would still add a boolean property (e.g. `updateRelatedObjects`) that guards this behaviour with default value `false`. Also the properties in the reference are actually meant to be "properties of the relation" and not "properties of the related object".

I know that carrier is using the updateMetadata extensively (900 call per minute) AND they use referenced resources. Not sure however if they use extra properties on the references.

2022-08-17 11:22 UTC, paul-cioroianu-waylay commented on plugins/updateMetadata/updateMetadataRecursively.test.js
> +    await expect(runPlug(script, options, waylay)).resolves.toEqual({ "observedState": "Success", "rawData": { "response": {} } })
dont know why, but it seems it was defined like this in the beginning
`send(null, { observedState: 'Success', rawData: { response } })`
instead of 
send(null, { observedState: 'Success', rawData:  response  })

so that part of the contract was not changed.

2022-08-17 11:37 UTC, paul-cioroianu-waylay commented
@brunoballekens  I'm sorry, but this part is not clear to me `Also the properties in the reference are actually meant to be "properties of the relation" and not "properties of the related object".` 
What do you mean by properties of the relation? How are they defined specifically? Is there a way to get only these properties based on a relation between A->B resources?

2022-08-17 11:46 UTC, brunoballekens commented
@paul-cioroianu-waylay I mean conceptually, like https://www.geeksforgeeks.org/attributes-to-relationships-in-er-model/. References where meant to model relations between resources and the properties on the reference as attributes to that relation.
An it is actually possible to search for all resources that have a relation in the `theRelation` with property `startDate > 123456789` by `/api/resources?query=theRelation.startDate:gt(123456789)`

2022-08-17 15:18 UTC, brunoballekens reviewed
cool.
We should still add `deepMerge` configuration metadata

2022-08-18 08:25 UTC, brunoballekens approved these changes
👍

2022-08-18 08:34 UTC, merged